Repository sismo-core/sismo-hub, pull requests merged in 2023-02, with the labels that each got.

#1293 feat: migrate groupId from uuid to uint128
  badges-metadata/base/hydra-s1/hydra-s1-offchain-attester.ts
  badges-metadata/local/hydra-s1-accountbound.ts
  badges-metadata/main/hydra-s1-accountbound.ts
  badges-metadata/playground/hydra-s1-accountbound.ts
  badges-metadata/staging/hydra-s1-accountbound.ts
  group-generators/generators/local-group/index.ts
  src/cli/command.ts
  src/file-store/file-store.ts
  src/infrastructure/file-store/file-store.test.ts
  src/infrastructure/file-store/local-file-store.test.ts
  src/infrastructure/file-store/local-file-store.ts
  src/infrastructure/file-store/memory-file-store.ts
  src/infrastructure/file-store/s3-file-store.test.ts
  src/infrastructure/file-store/s3-file-store.ts
  src/infrastructure/group-snapshot/dynamodb-group-snapshot-store.test.ts
  src/infrastructure/group-snapshot/dynamodb-group-snapshot-store.ts
  src/infrastructure/group-snapshot/group-snapshot-memory.ts
  src/infrastructure/group-snapshot/group-snapshot-store.test.ts
  src/infrastructure/group-snapshot/local-group-snapshot-store.ts
  src/infrastructure/group-store/dynamodb-group-store.test.ts
  src/infrastructure/group-store/dynamodb-group-store.ts
  src/infrastructure/group-store/group-store.test.ts
  src/infrastructure/group-store/local-group-store.ts
  src/infrastructure/group-store/memory-group-store.ts
  src/migration/02162023/migrate-groups-dynamodb-02162023.migration-test.ts
  src/migration/02172023/migrate-groups-dynamodb-02172023.migration-test.ts
  src/migration/02172023/migrate-groups-dynamodb-02172023.script.ts
  src/migration/02172023/migrate-groups-dynamodb-02172023.ts
  src/migration/12212022/migrate-groups-dynamodb-12212022.ts
  src/topics/group-generator/group-generator.test.ts
  src/topics/group-generator/group-generator.ts
  src/topics/group-snapshot/group-snapshot.api.test.ts
  src/topics/group-snapshot/group-snapshot.api.ts
  src/topics/group-snapshot/group-snapshot.schema.ts
  src/topics/group-snapshot/group-snapshot.store.ts
  src/topics/group/group.api.schema.ts
  src/topics/group/group.api.test.ts
  src/topics/group/group.api.ts
  src/topics/group/group.store.ts
Labels: DO NOT MERGE

#1347 feat: add zohal-KYC group on Gnosis, Mumbai, Polygon and Goerli
  badges-metadata/main/hydra-s1-accountbound.ts
  flows/main.ts
  group-generators/generators/index.ts
  group-generators/generators/zohal-KYC/index.ts
  static/badges/zohal-KYC.svg
Labels: gnosis, testnets, polygon

#1299 Web3 social group
  .github/actions/generate-group-send-on-chain/action.yml
  .github/actions/update-groups-send-on-chain/action.yml
  .github/workflows/check-new-groups-generation.yml
  .github/workflows/generate_group_prod.yml
  .github/workflows/generate_group_staging.yml
  .github/workflows/generate_group_testnets.yml
  .github/workflows/update_groups_daily_prod.yml
  .github/workflows/update_groups_daily_staging.yml
  .github/workflows/update_groups_daily_testnets.yml
  .github/workflows/update_groups_weekly_prod.yml
  .github/workflows/update_groups_weekly_staging.yml
  .github/workflows/update_groups_weekly_testnets.yml
  group-generators/generators/index.ts
  group-generators/generators/web3-social/index.ts
  group-generators/helpers/data-providers/farcaster/index.ts
  group-generators/helpers/data-providers/farcaster/types.ts
  group-generators/helpers/data-providers/index.ts
  group-generators/helpers/data-providers/lens/index.ts
  group-generators/helpers/data-providers/utils/utils.ts
Labels: WIP
